apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hi2l3k4ug-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hi2l3k4ug-python 
  name: hi2l3k4ug-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hi2l3k4ug-python 
